// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7HpEF4RNLJeXuxDxfHzNU6UG7qehvSd0',
    appId: '1:976547159655:web:28b228d4b4ebf23224bec2',
    messagingSenderId: '976547159655',
    projectId: 'ballozee-salon-app',
    authDomain: 'ballozee-salon-app.firebaseapp.com',
    storageBucket: 'ballozee-salon-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXpV4eZmC66hHYKZ8B-QPFWHq-CsTvDY',
    appId: '1:976547159655:android:0acbb3098fa0bdec24bec2',
    messagingSenderId: '976547159655',
    projectId: 'ballozee-salon-app',
    storageBucket: 'ballozee-salon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jh4XAUJ6QTix9tpiLxbwEJu7ynCkmZM',
    appId: '1:976547159655:ios:e6cb90c70b201bdb24bec2',
    messagingSenderId: '976547159655',
    projectId: 'ballozee-salon-app',
    storageBucket: 'ballozee-salon-app.firebasestorage.app',
    iosBundleId: 'com.example.salonManagement',
  );
}
